name: TEST
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: testing passing value between steps
        run: |
          Write-Host $GITHUB_ENV
          Write-Host $env:GITHUB_ENV
          
          $versionNo = "1.2.3.4"
          Add-Content $GITHUB_ENV "artifact_version=$versionNo"
          
      - name: testing passing value between steps
        run: |
          Write-Host $env:artifact_version
          Write-Host ${ env.artifact_version }
          Write-Host ${{ env.artifact_version }}
